#cloud-config
users:
  - name: appuser
    shell: /bin/bash

package_upgrade: false

runcmd:
 - apt update
 - mkdir --mode=0777 /pgdata
 - mkdir /certs
 - mkdir --mode=0777 /tiles
 - usermod -aG docker appuser
 - chown -R appuser:appuser /certs
 - chown -R appuser:appuser /tiles
 - su - appuser -c "openssl genrsa -out /certs/portainer.key 2048" 
 - su - appuser -c "openssl ecparam -genkey -name secp384r1 -out /certs/portainer.key" 
 - su - appuser -c "openssl req -new -x509 -sha256 -key /certs/portainer.key -out /certs/portainer.crt -days 3650 -subj '/C=CH/ST=Solothurn/L=Solothurn/O=AGI/OU=SOGIS/CN=ssl.sogeo.services'" 
 - su - appuser -c "docker swarm init --advertise-addr $(hostname -I | awk '{print $1}')" 
 - su - appuser -c "docker volume create portainer_data" 
 - su - appuser -c "docker run -d -p 9443:9000 -p 8000:8000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v /certs:/certs -v portainer_data:/data portainer/portainer --ssl --sslcert /certs/portainer.crt --sslkey /certs/portainer.key" 